import { writeFile, mkdir } from "fs/promises";
import { join } from "path";
import type { GeneratedReport, ResearchSource } from "../types/index.js";
import { REPORTS_DIR } from "../constants/index.js";
import { formatSourceList } from "./dataFormatter.js";

// -------------------------------------------------------------------------
// Report Generator — saves reports as Markdown files
// -------------------------------------------------------------------------

export async function saveReport(report: GeneratedReport): Promise<string> {
  await mkdir(REPORTS_DIR, { recursive: true });
  const filename = generateFilename(report);
  const filepath = join(REPORTS_DIR, filename);
  const markdown = buildMarkdown(report);
  await writeFile(filepath, markdown, "utf-8");
  return filepath;
}

function generateFilename(report: GeneratedReport): string {
  const slug = report.query
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .slice(0, 50);
  const date = new Date(report.generatedAt).toISOString().split("T")[0];
  return `${report.type}_${date}_${slug}.md`;
}

function buildMarkdown(report: GeneratedReport): string {
  const typeLabel: Record<GeneratedReport["type"], string> = {
    market_research: "Market Research Report",
    competitor_analysis: "Competitor Analysis Report",
    industry_report: "Industry Report",
    trend_analysis: "Trend Analysis Report",
  };

  const lines = [
    `# ${typeLabel[report.type]}`,
    `**Query:** ${report.query}`,
    `**Generated:** ${new Date(report.generatedAt).toLocaleString()}`,
    "",
    "---",
    "",
    report.content,
    "",
    "---",
    "",
    "## Sources",
    "",
    formatSourceList(report.sources),
    "",
    `*Report generated by Deep Research Analyst Agent*`,
  ];

  return lines.join("\n");
}

export function buildReport(
  type: GeneratedReport["type"],
  query: string,
  content: string,
  sources: ResearchSource[]
): GeneratedReport {
  return {
    title: `${type.replace(/_/g, " ")} — ${query}`,
    type,
    generatedAt: new Date().toISOString(),
    query,
    content,
    sources,
  };
}
